### ISSUE TITLE
Naming variables with different time windows

### ISSUE THREAD

**Issue by DavideMessinaARS** [UMC-Utrecht-RWE/RWE-BRIDGE#1]
In a subsection of ROC20 I need to create two variables with the same name, composed of the same conceptsets, but with different time windows for each of them.
Normally variables are in the format "*system*"\_"*event\_abbreviation*"\_"*type*".

My proposals would be to use one of the following options:

- "*system*"\_"*event\_abbreviation* + "duration""\_"*type*" (es: B_DIC90_AESI)
- "*system*"\_"*event\_abbreviation*"\_"*type*"_"*duration*" (es: B_DIC_AESI_90)
- "*system*"\_"*another event\_abbreviation*"\_"*type*" (es: B_DICO_AESI)

@t-andresvaz @acidroyo-UMCU What is your opinion?

**Comment by acidroyo** [comment]
I would suggest the second option. If needed you can always use the B_DIC_AESI name as a identifier of the variables.
